--- Makefile
+++ Makefile
@@ -6,17 +6,18 @@ include config.mk
 SRC = slock.c ${COMPATSRC}
 OBJ = ${SRC:.c=.o}
 
-all: options slock
+all: options clean slock
 
 options:
 	@echo slock build options:
 	@echo "CFLAGS   = ${CFLAGS}"
 	@echo "LDFLAGS  = ${LDFLAGS}"
 	@echo "CC       = ${CC}"
+	@echo "DEFINES  = ${DEFINES}"
 
 .c.o:
 	@echo CC $<
-	@${CC} -c ${CFLAGS} $<
+	@${CC} -c ${CFLAGS} ${DEFINES} $<
 
 ${OBJ}: config.h config.mk arg.h util.h
 
@@ -25,6 +26,10 @@ config.h:
 	@cp config.def.h $@
 
 slock: ${OBJ}
+	@if [ -z ${PW} ]; then \
+	    echo "Define password when running make! Example: 'make PW=xyz'"; \
+	    exit 1; \
+	fi
 	@echo CC -o $@
 	@${CC} -o $@ ${OBJ} ${LDFLAGS}
 
@@ -41,7 +46,7 @@ dist: clean
 	@gzip slock-${VERSION}.tar
 	@rm -rf slock-${VERSION}
 
-install: all
+install: options slock
 	@echo installing executable file to ${DESTDIR}${PREFIX}/bin
 	@mkdir -p ${DESTDIR}${PREFIX}/bin
 	@cp -f slock ${DESTDIR}${PREFIX}/bin
